<?php
// $Id$

/**
 * @file
 * Ocean Libarian module file
 *
 * Ocean Librarian module - provides services for managing the Ocean distributed library.
 */

 // help section
 //================ 


/**
 * Implementation of hook_help().
 */
function ocean_librarian_help($path, $arg) {
  switch ($path) {
    case 'admin/help#ocean_librarian':
      $output = '<p>'. t('The <em>Ocean Librarian</em> module provides services for managing the distributed Ocean library.') .'</p>';
      return $output;
  }
}

 // permissions? are permissions required to add keywords?
 //================



 // menu section
 //================

/**
 * Implementation of hook_menu()
 */
function ocean_librarian_menu() {
 // add tab to page for page stats?
}



 // settings form (to be added to Keyword Targets settings)
 //================

/*
 * Implementation of hook_form_FORM_ID_alter to add elements to the Keyword Targets settings form
 */
function ocean_librarian_settings() {
  /*
  $form['search']  = array(
    '#type'         => 'fieldset',
    '#title'        => t('Search Suggest'),   
  ); 
  
  $form['search']['log_file_import'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Import Log File'),
    '#default_value' => '',
    '#description'  => t('Full local path or URL to log file you with to import'),
   // '#validate' ?     =>
  );

 $form['#submit'][] = 'ocean_librarian_settings_submit';
 */
}


 // global hooks
 //================

 // on node delete, remove links to that node?
function ocean_librarian_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
 // do we want to delete statistics for nodes that have been deleted?
}




 // scheduled cron tasts
 //================

 // periodically update list and add suggestions (maybe hourly? daily? user setting?)

 // periodically parse log file and import results? as option to jquery?




 // general reports?
 //================

 // provide search performance chart?




 // api ?
 //================


